### ISSUE TITLE
能上传一段respeaker mic的录音数据吗，给odas 项目 debug 测试吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [xiongyihui/notes#18]
你好，在 https://github.com/introlab/odas 项目中看到你的活动，我对这个项目也非常感兴趣，希望可以调试理解里面的算法，但我目前没有硬件，没有录音数据，没办法运行程序，你能上传一些匹配下面两个配置文件的音频数据吗？ 谢谢了！
  config\odaslive\respeaker.cfg
  config\odaslive\respeaker_4_mic_array.cfg

**Comment by xiongyihui** [comment]
下面是一段 respeaker 4 mic array的录音，试试

[4mic_S32_LE_48000.zip](https://github.com/xiongyihui/notes/files/2248470/4mic_S32_LE_48000.zip)

**Comment by zuowanbushiwo** [comment]
非常感谢，刚刚测试已经能运行了，能检测到声源。
